name = "Level 2"

textures = [
	{ id = "tilemap", file = "../assets/tilemap.png" },
	{ id = "player", file = "../assets/shadow.png" },
	{ id = "shadow", file = "../assets/player.png" },
	{ id = "player2", file = "../assets/player.png" },
	{ id = "player3", file = "../assets/player.png" },
	{ id = "player4", file = "../assets/player.png" },
	{ id = "player5", file = "../assets/player.png" },
	{ id = "player6", file = "../assets/player.png" },
	{ id = "player7", file = "../assets/player.png" },
	{ id = "player8", file = "../assets/player.png" },
	{ id = "player9", file = "../assets/player.png" },
	{ id = "player10", file = "../assets/player.png" },
	{ id = "player11", file = "../assets/player.png" },
	{ id = "player12", file = "../assets/player.png" },
	{ id = "player13", file = "../assets/player.png" },
	{ id = "player14", file = "../assets/player.png" },
	{ id = "player15", file = "../assets/player.png" },
	{ id = "player16", file = "../assets/player.png" },
	{ id = "player17", file = "../assets/player.png" },
	{ id = "player18", file = "../assets/player.png" },
	{ id = "player19", file = "../assets/player.png" },
	{ id = "player20", file = "../assets/player.png" },
	{ id = "player21", file = "../assets/player.png" },
	{ id = "player22", file = "../assets/player.png" },
	{ id = "player23", file = "../assets/player.png" },
	{ id = "player24", file = "../assets/player.png" },
	{ id = "player25", file = "../assets/player.png" },
	{ id = "player26", file = "../assets/player.png" },
	{ id = "player27", file = "../assets/player.png" },
	{ id = "player28", file = "../assets/player.png" },
	{ id = "player29", file = "../assets/player.png" },
	{ id = "player30", file = "../assets/player.png" },
	{ id = "player31", file = "../assets/player.png" },
	{ id = "player32", file = "../assets/player.png" },
	{ id = "player33", file = "../assets/player.png" },
	{ id = "player34", file = "../assets/player.png" },
	{ id = "player35", file = "../assets/player.png" },
	{ id = "player36", file = "../assets/player.png" },
	{ id = "player37", file = "../assets/player.png" },
	{ id = "player38", file = "../assets/player.png" },
	{ id = "player39", file = "../assets/player.png" },
	{ id = "player40", file = "../assets/player.png" },
	{ id = "player41", file = "../assets/player.png" },
	{ id = "player42", file = "../assets/player.png" },
	{ id = "player43", file = "../assets/player.png" },
	{ id = "player44", file = "../assets/player.png" },
	{ id = "player45", file = "../assets/player.png" },
	{ id = "player46", file = "../assets/player.png" },
	{ id = "player47", file = "../assets/player.png" },
	{ id = "player48", file = "../assets/player.png" },
	{ id = "player49", file = "../assets/player.png" },
	{ id = "player50", file = "../assets/player.png" },
	{ id = "player51", file = "../assets/player.png" },
]

fonts = [
	{ id = "bigblue48", file = "../assets/fonts/bigblue.ttf", fontSize = 48 },
	{ id = "bigblue12", file = "../assets/fonts/bigblue.ttf", fontSize = 12 }
]

[tilemap]
map = "assets/tilemaps/demo.map"
texture = "tilemap"
scale = 4
tileSize = 16
cols = 30
rows = 17

[[entities]]
tag = "player"
[[entities.components]]
type = "TransformComponent"
params = [
	{ key = "position.x", value = 1000, type = "int" },
	{ key = "position.y", value = 0, type = "int" },
	{ key = "scale.x", value = 4, type = "int" },
	{ key = "scale.y", value = 4, type = "int" },
	{ key = "angle", value = 0.0, type = "float" }
]
[[entities.components]]
type = "SpriteComponent"
params = [
	{ key = "width", value = 83, type = "int" },
	{ key = "height", value = 40, type = "int" },
	{ key = "id", value = "player", type = "string" },
	{ key = "zIndex", value = 3, type = "int" },
	{ key = "isFixed", value = false, type = "bool" },
	{ key = "srcRect.x", value = 0, type = "int" },
	{ key = "srcRect.y", value = 0, type = "int" },
	{ key = "isFlipped", value = false, type = "bool" }
]
[[entities.components]]
type = "AnimationComponent"
params = [
	{ key = "frames", value = [5, 6, 7, 5, 3, 5, 6], type = "int_array" },
	{ key = "speeds", value = [8, 8, 15, 8, 12, 8, 8], type = "int_array" },
	{ key = "loops", value = [true, true, true, true, false, true, true], type = "bool_array" },
	{ key = "srcRect.x", value = 0, type = "int" },
	{ key = "srcRect.y", value = 0, type = "int" },
	{ key = "spaceBetweenFrames.x", value = 0, type = "int" },
	{ key = "spaceBetweenFrames.y", value = 0, type = "int" }
]
[[entities.components]]
type = "RigidBodyComponent"
params = [
	{ key = "velocity.x", value = 0, type = "int" },
	{ key = "velocity.y", value = 0, type = "int" },
	{ key = "acceleration.x", value = 0, type = "int"},
	{ key = "acceleration.y", value = 1500, type = "int"},
	{ key = "maxVelocity.x", value = 450, type = "int"},
	{ key = "maxVelocity.y", value = 1200, type = "int"}
]
[[entities.components]]
type = "BoxColliderComponent"
params = [
	{ key = "x", value = 37, type = "int" },
	{ key = "y", value = 16, type = "int" },
	{ key = "width", value = 8, type = "int" },
	{ key = "height", value = 18, type = "int" }
]
[[entities.components]]
type = "PlayerController"
params = [
	{ key = "ignoreInput", value = false, type = "bool" },
]

[[entities]]
group = "walls"
[[entities.components]]
type = "TransformComponent"
params = [
	{ key = "position.x", value = 1796, type = "int" },
	{ key = "position.y", value = 0, type = "int" },
	{ key = "scale.x", value = 1, type = "int" },
	{ key = "scale.y", value = 1, type = "int" },
	{ key = "angle", value = 0.0, type = "float" }
]
[[entities.components]]
type = "BoxColliderComponent"
params = [
	{ key = "x", value = 0, type = "int" },
	{ key = "y", value = 0, type = "int" },
	{ key = "width", value = 124, type = "int" },
	{ key = "height", value = 638, type = "int" }
]

[[entities]]
group = "walls"
[[entities.components]]
type = "TransformComponent"
params = [
	{ key = "position.x", value = 0, type = "int" },
	{ key = "position.y", value = 0, type = "int" },
	{ key = "scale.x", value = 1, type = "int" },
	{ key = "scale.y", value = 1, type = "int" },
	{ key = "angle", value = 0.0, type = "float" }
]
[[entities.components]]
type = "BoxColliderComponent"
params = [
	{ key = "x", value = 1, type = "int" },
	{ key = "y", value = 1, type = "int" },
	{ key = "width", value = 252, type = "int" },
	{ key = "height", value = 1080, type = "int" }
]

[[entities]]
group = "walls"
[[entities.components]]
type = "TransformComponent"
params = [
	{ key = "position.x", value = 254, type = "int" },
	{ key = "position.y", value = 832, type = "int" },
	{ key = "scale.x", value = 1, type = "int" },
	{ key = "scale.y", value = 1, type = "int" },
	{ key = "angle", value = 0.0, type = "float" }
]
[[entities.components]]
type = "BoxColliderComponent"
params = [
	{ key = "x", value = 0, type = "int" },
	{ key = "y", value = 0, type = "int" },
	{ key = "width", value = 1666, type = "int" },
	{ key = "height", value = 248, type = "int" }
]

[[entities]]
group = "walls"
[[entities.components]]
type = "TransformComponent"
params = [
	{ key = "position.x", value = 384, type = "int" },
	{ key = "position.y", value = 448, type = "int" },
	{ key = "scale.x", value = 1, type = "int" },
	{ key = "scale.y", value = 1, type = "int" },
	{ key = "angle", value = 0.0, type = "float" }
]
[[entities.components]]
type = "BoxColliderComponent"
params = [
	{ key = "x", value = 0, type = "int" },
	{ key = "y", value = 0, type = "int" },
	{ key = "width", value = 384, type = "int" },
	{ key = "height", value = 60, type = "int" }
]

[[entities]]
group = "walls"
[[entities.components]]
type = "TransformComponent"
params = [
	{ key = "position.x", value = 1344, type = "int" },
	{ key = "position.y", value = 448, type = "int" },
	{ key = "scale.x", value = 1, type = "int" },
	{ key = "scale.y", value = 1, type = "int" },
	{ key = "angle", value = 0.0, type = "float" }
]
[[entities.components]]
type = "BoxColliderComponent"
params = [
	{ key = "x", value = 0, type = "int" },
	{ key = "y", value = 0, type = "int" },
	{ key = "width", value = 384, type = "int" },
	{ key = "height", value = 60, type = "int" }
]

[[entities]]
group = "walls"
[[entities.components]]
type = "TransformComponent"
params = [
	{ key = "position.x", value = 896, type = "int" },
	{ key = "position.y", value = 640, type = "int" },
	{ key = "scale.x", value = 1, type = "int" },
	{ key = "scale.y", value = 1, type = "int" },
	{ key = "angle", value = 0.0, type = "float" }
]
[[entities.components]]
type = "BoxColliderComponent"
params = [
	{ key = "x", value = 0, type = "int" },
	{ key = "y", value = 0, type = "int" },
	{ key = "width", value = 322, type = "int" },
	{ key = "height", value = 60, type = "int" }
]
