name = "Level 1"

textures = [
	{ id = "tilemap", file = "../assets/tilemap.png" },
	{ id = "player", file = "../assets/player.png" },
]

fonts = [
# 	{ id = "bigblue48", file = "../assets/fonts/bigblue.ttf", fontSize = 48 },
# 	{ id = "bigblue12", file = "../assets/fonts/bigblue.ttf", fontSize = 12 }
]

[tilemap]
map = "assets/tilemaps/demo.map"
texture = "tilemap"
scale = 4
tileSize = 16
cols = 30
rows = 17

[[entities]]
tag = "player"
[[entities.components]]
type = "TransformComponent"
params = [
	{ key = "position.x", value = 500, type = "int" },
	{ key = "position.y", value = 312, type = "int" },
	{ key = "scale.x", value = 4, type = "int" },
	{ key = "scale.y", value = 4, type = "int" },
	{ key = "angle", value = 0.0, type = "float" }
	# 0, 0, 4, 4, 0.0
]
[[entities.components]]
type = "SpriteComponent"
# params = [ 13, 18, "player", 1, false, 34, 16]
params = [
	{ key = "width", value = 83, type = "int" },
	{ key = "height", value = 40, type = "int" },
	{ key = "id", value = "player", type = "string" },
	{ key = "zIndex", value = 3, type = "int" },
	{ key = "isFixed", value = false, type = "bool" },
	{ key = "srcRect.x", value = 0, type = "int" },
	{ key = "srcRect.y", value = 0, type = "int" }
]
[[entities.components]]
type = "AnimationComponent"
params = [
	{ key = "frames", value = [5, 6, 7, 5, 3, 5, 6], type = "int_array" },
	{ key = "speeds", value = [8, 8, 15, 8, 8, 8, 8], type = "int_array" },
	{ key = "loops", value = [true, true, true, true, false, true, true], type = "bool_array" },
	{ key = "srcRect.x", value = 0, type = "int" },
	{ key = "srcRect.y", value = 0, type = "int" },
	{ key = "spaceBetweenFrames.x", value = 0, type = "int" },
	{ key = "spaceBetweenFrames.y", value = 0, type = "int" }
]
[[entities.components]]
type = "RigidBodyComponent"
params = [
	{ key = "velocity.x", value = 100, type = "int" },
	{ key = "velocity.y", value = 0, type = "int" }
]
[[entities.components]]
type = "BoxColliderComponent"
params = [
	{ key = "x", value = 35, type = "int" },
	{ key = "y", value = 16, type = "int" },
	{ key = "width", value = 13, type = "int" },
	{ key = "height", value = 18, type = "int" }
]
