name = "Level 1"

[[entities]]
tag = "player"

[[entities.components]]
type = "TransformComponent"

params = [
{type="int",value=500,key="position.x"},
{type="int",value=0,key="position.y"},
{type="int",value=4,key="scale.x"},
{type="int",value=4,key="scale.y"},
{type="float",value=0.0,key="angle"},
]

[[entities.components]]
type = "SpriteComponent"

params = [
{type="int",value=83,key="width"},
{type="int",value=40,key="height"},
{type="string",value="player",key="id"},
{type="int",value=7,key="zIndex"},
{type="bool",value=false,key="isFixed"},
{type="int",value=0,key="srcRect.x"},
{type="int",value=0,key="srcRect.y"},
{type="bool",value=false,key="isFlipped"},
]

[[entities.components]]
type = "AnimationComponent"

params = [
{type="int_array",value=[5,6,7,5,3,5,6],key="frames"},
{type="int_array",value=[8,8,15,8,12,8,8],key="speeds"},
{type="bool_array",value=[true,true,true,true,false,true,true],key="loops"},
{type="int",value=0,key="srcRect.x"},
{type="int",value=0,key="srcRect.y"},
{type="int",value=0,key="spaceBetweenFrames.x"},
{type="int",value=0,key="spaceBetweenFrames.y"},
]

[[entities.components]]
type = "RigidBodyComponent"

params = [
{type="int",value=0,key="velocity.x"},
{type="int",value=0,key="velocity.y"},
{type="int",value=0,key="acceleration.x"},
{type="int",value=1500,key="acceleration.y"},
{type="int",value=450,key="maxVelocity.x"},
{type="int",value=1200,key="maxVelocity.y"},
]

[[entities.components]]
type = "BoxColliderComponent"

params = [
{type="int",value=37,key="x"},
{type="int",value=16,key="y"},
{type="int",value=8,key="width"},
{type="int",value=18,key="height"},
]

[[entities.components]]
type = "PlayerController"

params = [
{type="bool",value=false,key="ignoreInput"},
]

[[entities]]
group = "walls"

[[entities.components]]
type = "TransformComponent"

params = [
{type="int",value=1796,key="position.x"},
{type="int",value=0,key="position.y"},
{type="int",value=1,key="scale.x"},
{type="int",value=1,key="scale.y"},
{type="float",value=0.0,key="angle"},
]

[[entities.components]]
type = "BoxColliderComponent"

params = [
{type="int",value=0,key="x"},
{type="int",value=0,key="y"},
{type="int",value=124,key="width"},
{type="int",value=638,key="height"},
]

[[entities]]
group = "walls"

[[entities.components]]
type = "TransformComponent"

params = [
{type="int",value=0,key="position.x"},
{type="int",value=0,key="position.y"},
{type="int",value=1,key="scale.x"},
{type="int",value=1,key="scale.y"},
{type="float",value=0.0,key="angle"},
]

[[entities.components]]
type = "BoxColliderComponent"

params = [
{type="int",value=1,key="x"},
{type="int",value=1,key="y"},
{type="int",value=252,key="width"},
{type="int",value=1080,key="height"},
]

[[entities]]
group = "walls"

[[entities.components]]
type = "TransformComponent"

params = [
{type="int",value=254,key="position.x"},
{type="int",value=832,key="position.y"},
{type="int",value=1,key="scale.x"},
{type="int",value=1,key="scale.y"},
{type="float",value=0.0,key="angle"},
]

[[entities.components]]
type = "BoxColliderComponent"

params = [
{type="int",value=0,key="x"},
{type="int",value=0,key="y"},
{type="int",value=1666,key="width"},
{type="int",value=248,key="height"},
]

[[entities]]
group = "walls"

[[entities.components]]
type = "TransformComponent"

params = [
{type="int",value=384,key="position.x"},
{type="int",value=448,key="position.y"},
{type="int",value=1,key="scale.x"},
{type="int",value=1,key="scale.y"},
{type="float",value=0.0,key="angle"},
]

[[entities.components]]
type = "BoxColliderComponent"

params = [
{type="int",value=0,key="x"},
{type="int",value=0,key="y"},
{type="int",value=384,key="width"},
{type="int",value=60,key="height"},
]

[[entities]]
group = "walls"

[[entities.components]]
type = "TransformComponent"

params = [
{type="int",value=1344,key="position.x"},
{type="int",value=448,key="position.y"},
{type="int",value=1,key="scale.x"},
{type="int",value=1,key="scale.y"},
{type="float",value=0.0,key="angle"},
]

[[entities.components]]
type = "BoxColliderComponent"

params = [
{type="int",value=0,key="x"},
{type="int",value=0,key="y"},
{type="int",value=384,key="width"},
{type="int",value=60,key="height"},
]

[[entities]]
group = "walls"

[[entities.components]]
type = "TransformComponent"

params = [
{type="int",value=896,key="position.x"},
{type="int",value=640,key="position.y"},
{type="int",value=1,key="scale.x"},
{type="int",value=1,key="scale.y"},
{type="float",value=0.0,key="angle"},
]

[[entities.components]]
type = "BoxColliderComponent"

params = [
{type="int",value=0,key="x"},
{type="int",value=0,key="y"},
{type="int",value=322,key="width"},
{type="int",value=60,key="height"},
]

[tilemap]
rows = 17
cols = 30
scale = 4
tileSize = 16
texture = "tilemap"
map = "assets/tilemaps/demo.map"

[[fonts]]
fontSize = 48
file = "../assets/fonts/bigblue.ttf"
id = "bigblue48"
[[fonts]]
fontSize = 12
file = "../assets/fonts/bigblue.ttf"
id = "bigblue12"

[[textures]]
file = "../assets/tilemap.png"
id = "tilemap"
[[textures]]
file = "../assets/player.png"
id = "player"
[[textures]]
file = "../assets/shadow.png"
id = "shadow"

